// AUTO-GENERATED by scripts/generate-tools.ts from openapi.yaml. DO NOT EDIT.
//
// Run `npm run generate` to regenerate. 40 tools. The write set is
// exactly the 11 operations that declare a required Idempotency-Key header
// (annotate_transaction, categorize_transactions, create_category, create_transaction, delete_category, delete_transaction, record_goal_contribution, switch_budget_method, update_category, update_goal, update_transaction).
// Of those, delete_category, delete_transaction, switch_budget_method are
// marked destructive: they remove or replace something the user already had.

import { z } from "zod";
import { descriptions } from "../descriptions.js";
import type { ToolSpec } from "./types.js";

export const tools: ToolSpec[] = [
  {
    toolName: "annotate_transaction",
    operationId: "annotateTransaction",
    method: "POST",
    path: "/v1/transactions/{id}/annotate",
    isWrite: true,
    destructive: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: ["category_id", "tags", "memo", "location", "clear_location"],
    description: descriptions.annotateTransaction,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      category_id: z.string().uuid().optional(),
      tags: z
        .array(z.string())
        .describe("Replaces every tag. An empty array clears them all.")
        .optional(),
      memo: z.string().describe("An empty string clears the memo.").optional(),
      location: z
        .object({
          street: z.string().optional(),
          city: z.string().optional(),
          state: z.string().optional(),
          postal_code: z.string().optional(),
          country: z.string().optional(),
        })
        .describe(
          'A purchase location. Redacted as a single unit (transaction.location) — a city plus a postal code answers "where were you" as surely as a street line does, so the components are never hidden separately. On a write it is GROUP-REPLACE: the components sent become the whole stored location and omitted ones are cleared. Use clear_location to remove it entirely.',
        )
        .optional(),
      clear_location: z.boolean().optional(),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
  {
    toolName: "categorize_transactions",
    operationId: "categorizeTransactions",
    method: "POST",
    path: "/v1/transactions/categorize",
    isWrite: true,
    destructive: false,
    pathParams: [],
    queryParams: [],
    bodyParams: ["items"],
    description: descriptions.categorizeTransactions,
    inputShape: {
      items: z.array(
        z
          .object({
            transaction_id: z.string().uuid(),
            category_id: z.string().uuid(),
            expected_version: z
              .number()
              .int()
              .describe(
                "Optional per item. Omit to apply regardless of the stored version; send it to have THIS item come back version_conflict rather than overwrite a change you did not see.",
              )
              .optional(),
          })
          .describe("One assignment in a bulk categorize."),
      ),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
  {
    toolName: "compute_debt_payoff_plan",
    operationId: "computeDebtPayoffPlan",
    method: "POST",
    path: "/v1/debt/payoff-plan",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: [],
    bodyParams: [
      "liability_ids",
      "strategy",
      "custom_order",
      "total_monthly_budget",
      "extra_monthly_payment",
    ],
    description: descriptions.computeDebtPayoffPlan,
    inputShape: {
      liability_ids: z.array(z.string().uuid()).optional(),
      strategy: z.enum(["snowball", "avalanche", "custom"]).optional(),
      custom_order: z
        .array(z.string().uuid())
        .describe("The explicit payoff order when strategy is custom.")
        .optional(),
      total_monthly_budget: z.string().describe("A decimal amount string.").optional(),
      extra_monthly_payment: z.string().describe("A decimal amount string.").optional(),
    },
  },
  {
    toolName: "create_category",
    operationId: "createCategory",
    method: "POST",
    path: "/v1/categories",
    isWrite: true,
    destructive: false,
    pathParams: [],
    queryParams: [],
    bodyParams: ["name", "parent_id", "icon", "color"],
    description: descriptions.createCategory,
    inputShape: {
      name: z.string(),
      parent_id: z.string().uuid().optional(),
      icon: z.string().describe('A Material icon name, or "emoji:<grapheme>".').optional(),
      color: z.string().describe('A hex color, e.g. "#FF5733".').optional(),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
  {
    toolName: "create_transaction",
    operationId: "createTransaction",
    method: "POST",
    path: "/v1/transactions",
    isWrite: true,
    destructive: false,
    pathParams: [],
    queryParams: [],
    bodyParams: [
      "account_id",
      "amount",
      "currency_code",
      "merchant",
      "description",
      "date",
      "category_id",
      "tags",
      "memo",
      "location",
    ],
    description: descriptions.createTransaction,
    inputShape: {
      account_id: z.string().uuid(),
      amount: z.string().describe("A decimal amount string, negative for spending. Never a float."),
      currency_code: z
        .string()
        .describe("ISO 4217 code. Defaults to the account's currency.")
        .optional(),
      merchant: z.string().optional(),
      description: z.string().optional(),
      date: z.string().describe("YYYY-MM-DD."),
      category_id: z.string().uuid().optional(),
      tags: z.array(z.string()).optional(),
      memo: z.string().optional(),
      location: z
        .object({
          street: z.string().optional(),
          city: z.string().optional(),
          state: z.string().optional(),
          postal_code: z.string().optional(),
          country: z.string().optional(),
        })
        .describe(
          'A purchase location. Redacted as a single unit (transaction.location) — a city plus a postal code answers "where were you" as surely as a street line does, so the components are never hidden separately. On a write it is GROUP-REPLACE: the components sent become the whole stored location and omitted ones are cleared. Use clear_location to remove it entirely.',
        )
        .optional(),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
  {
    toolName: "delete_category",
    operationId: "deleteCategory",
    method: "DELETE",
    path: "/v1/categories/{id}",
    isWrite: true,
    destructive: true,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: ["merge_into_category_id"],
    description: descriptions.deleteCategory,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      merge_into_category_id: z.string().uuid().optional(),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
  {
    toolName: "delete_transaction",
    operationId: "deleteTransaction",
    method: "DELETE",
    path: "/v1/transactions/{id}",
    isWrite: true,
    destructive: true,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [],
    description: descriptions.deleteTransaction,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
  {
    toolName: "get_account",
    operationId: "getAccount",
    method: "GET",
    path: "/v1/accounts/{id}",
    isWrite: false,
    destructive: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getAccount,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
    },
  },
  {
    toolName: "get_account_balances",
    operationId: "getAccountBalances",
    method: "GET",
    path: "/v1/accounts/{id}/balances",
    isWrite: false,
    destructive: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getAccountBalances,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
    },
  },
  {
    toolName: "get_budget",
    operationId: "getBudget",
    method: "GET",
    path: "/v1/budgets/{id}",
    isWrite: false,
    destructive: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getBudget,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
    },
  },
  {
    toolName: "get_budget_progress",
    operationId: "getBudgetProgress",
    method: "GET",
    path: "/v1/budgets/{id}/progress",
    isWrite: false,
    destructive: false,
    pathParams: ["id"],
    queryParams: ["month"],
    bodyParams: [],
    description: descriptions.getBudgetProgress,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      month: z
        .string()
        .describe("The month to report, as YYYY-MM. Defaults to the current month.")
        .optional(),
    },
  },
  {
    toolName: "get_cash_flow_forecast",
    operationId: "insightsCashFlowForecast",
    method: "GET",
    path: "/v1/insights/cash-flow-forecast",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["days_ahead", "account_id"],
    bodyParams: [],
    description: descriptions.insightsCashFlowForecast,
    inputShape: {
      days_ahead: z.number().int().min(1).describe("How many days ahead to project.").optional(),
      account_id: z.string().uuid().optional(),
    },
  },
  {
    toolName: "get_debt_summary",
    operationId: "getDebtSummary",
    method: "GET",
    path: "/v1/debt/summary",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getDebtSummary,
    inputShape: {},
  },
  {
    toolName: "get_goal",
    operationId: "getGoal",
    method: "GET",
    path: "/v1/goals/{id}",
    isWrite: false,
    destructive: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getGoal,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
    },
  },
  {
    toolName: "get_goal_history",
    operationId: "getGoalHistory",
    method: "GET",
    path: "/v1/goals/{id}/history",
    isWrite: false,
    destructive: false,
    pathParams: ["id"],
    queryParams: ["start_date", "end_date", "resolution"],
    bodyParams: [],
    description: descriptions.getGoalHistory,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      start_date: z.string().describe("Inclusive start date (YYYY-MM-DD)."),
      end_date: z.string().describe("Inclusive end date (YYYY-MM-DD).").optional(),
      resolution: z.enum(["daily", "weekly", "monthly"]).optional(),
    },
  },
  {
    toolName: "get_goal_progress",
    operationId: "getGoalProgress",
    method: "GET",
    path: "/v1/goals/{id}/progress",
    isWrite: false,
    destructive: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getGoalProgress,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
    },
  },
  {
    toolName: "get_income_vs_expenses",
    operationId: "insightsIncomeVsExpenses",
    method: "GET",
    path: "/v1/insights/income-vs-expenses",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["start_date", "end_date"],
    bodyParams: [],
    description: descriptions.insightsIncomeVsExpenses,
    inputShape: {
      start_date: z.string().describe("Inclusive start date (YYYY-MM-DD)."),
      end_date: z.string().describe("Inclusive end date (YYYY-MM-DD)."),
    },
  },
  {
    toolName: "get_month_summary",
    operationId: "insightsMonthSummary",
    method: "GET",
    path: "/v1/insights/month-summary",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["month"],
    bodyParams: [],
    description: descriptions.insightsMonthSummary,
    inputShape: {
      month: z.string().describe("The month to summarize, as YYYY-MM."),
    },
  },
  {
    toolName: "get_net_worth",
    operationId: "getNetWorth",
    method: "GET",
    path: "/v1/net-worth",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getNetWorth,
    inputShape: {},
  },
  {
    toolName: "get_net_worth_history",
    operationId: "getNetWorthHistory",
    method: "GET",
    path: "/v1/net-worth/history",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["period", "base_currency"],
    bodyParams: [],
    description: descriptions.getNetWorthHistory,
    inputShape: {
      period: z
        .string()
        .describe("The look-back period token (for example 30d, 6mo, 1y).")
        .optional(),
      base_currency: z
        .string()
        .describe("The ISO 4217 currency the series is converted to.")
        .optional(),
    },
  },
  {
    toolName: "get_spending_by_category",
    operationId: "insightsSpendingByCategory",
    method: "GET",
    path: "/v1/insights/spending-by-category",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["start_date", "end_date"],
    bodyParams: [],
    description: descriptions.insightsSpendingByCategory,
    inputShape: {
      start_date: z.string().describe("Inclusive start date (YYYY-MM-DD)."),
      end_date: z.string().describe("Inclusive end date (YYYY-MM-DD)."),
    },
  },
  {
    toolName: "get_sync_status",
    operationId: "getSyncStatus",
    method: "GET",
    path: "/v1/sync-status",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getSyncStatus,
    inputShape: {},
  },
  {
    toolName: "get_transaction",
    operationId: "getTransaction",
    method: "GET",
    path: "/v1/transactions/{id}",
    isWrite: false,
    destructive: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getTransaction,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
    },
  },
  {
    toolName: "list_accounts",
    operationId: "listAccounts",
    method: "GET",
    path: "/v1/accounts",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["cursor", "page_size", "connection_id"],
    bodyParams: [],
    description: descriptions.listAccounts,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
      connection_id: z
        .string()
        .uuid()
        .describe("Filter to accounts under a single bank connection.")
        .optional(),
    },
  },
  {
    toolName: "list_budgets",
    operationId: "listBudgets",
    method: "GET",
    path: "/v1/budgets",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["cursor", "page_size", "active"],
    bodyParams: [],
    description: descriptions.listBudgets,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
      active: z.boolean().describe("When true, return only active budgets.").optional(),
    },
  },
  {
    toolName: "list_categories",
    operationId: "listCategories",
    method: "GET",
    path: "/v1/categories",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: [],
    bodyParams: [],
    description: descriptions.listCategories,
    inputShape: {},
  },
  {
    toolName: "list_connections",
    operationId: "listConnections",
    method: "GET",
    path: "/v1/connections",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["cursor", "page_size"],
    bodyParams: [],
    description: descriptions.listConnections,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
    },
  },
  {
    toolName: "list_goal_contributions",
    operationId: "getGoalContributions",
    method: "GET",
    path: "/v1/goals/{id}/contributions",
    isWrite: false,
    destructive: false,
    pathParams: ["id"],
    queryParams: ["cursor", "page_size"],
    bodyParams: [],
    description: descriptions.getGoalContributions,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
    },
  },
  {
    toolName: "list_goals",
    operationId: "listGoals",
    method: "GET",
    path: "/v1/goals",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["cursor", "page_size"],
    bodyParams: [],
    description: descriptions.listGoals,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
    },
  },
  {
    toolName: "list_holdings",
    operationId: "listHoldings",
    method: "GET",
    path: "/v1/holdings",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["cursor", "page_size", "account_id"],
    bodyParams: [],
    description: descriptions.listHoldings,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
      account_id: z.string().uuid().optional(),
    },
  },
  {
    toolName: "list_liabilities",
    operationId: "listLiabilities",
    method: "GET",
    path: "/v1/liabilities",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["cursor", "page_size", "account_id"],
    bodyParams: [],
    description: descriptions.listLiabilities,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
      account_id: z.string().uuid().optional(),
    },
  },
  {
    toolName: "list_recurring",
    operationId: "listRecurring",
    method: "GET",
    path: "/v1/recurring",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["cursor", "page_size"],
    bodyParams: [],
    description: descriptions.listRecurring,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
    },
  },
  {
    toolName: "list_transactions",
    operationId: "listTransactions",
    method: "GET",
    path: "/v1/transactions",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: [
      "cursor",
      "page_size",
      "account_id",
      "category_id",
      "start_date",
      "end_date",
      "pending",
      "source",
      "uncategorized",
    ],
    bodyParams: [],
    description: descriptions.listTransactions,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
      account_id: z.string().uuid().optional(),
      category_id: z.string().uuid().optional(),
      start_date: z.string().describe("Inclusive start date (YYYY-MM-DD).").optional(),
      end_date: z.string().describe("Inclusive end date (YYYY-MM-DD).").optional(),
      pending: z
        .boolean()
        .describe("When set, filter to pending (true) or posted (false) transactions.")
        .optional(),
      source: z.enum(["bank_sync", "manual", "import"]).optional(),
      uncategorized: z
        .boolean()
        .describe("When true, return only transactions with no category.")
        .optional(),
    },
  },
  {
    toolName: "list_upcoming_bills",
    operationId: "listUpcomingBills",
    method: "GET",
    path: "/v1/bills/upcoming",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["days_ahead"],
    bodyParams: [],
    description: descriptions.listUpcomingBills,
    inputShape: {
      days_ahead: z.number().int().min(1).describe("How many days ahead to project.").optional(),
    },
  },
  {
    toolName: "record_goal_contribution",
    operationId: "recordGoalContribution",
    method: "POST",
    path: "/v1/goals/{id}/contributions",
    isWrite: true,
    destructive: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: ["amount", "currency_code", "note", "period_start"],
    description: descriptions.recordGoalContribution,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      amount: z.string().describe("A positive decimal amount string."),
      currency_code: z
        .string()
        .describe("ISO 4217 code. Defaults to the goal's currency when omitted.")
        .optional(),
      note: z.string().optional(),
      period_start: z
        .string()
        .describe("The budget period (YYYY-MM-DD, first of month). Defaults to the current month.")
        .optional(),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
  {
    toolName: "search_transactions",
    operationId: "searchTransactions",
    method: "GET",
    path: "/v1/transactions/search",
    isWrite: false,
    destructive: false,
    pathParams: [],
    queryParams: ["q", "cursor", "page_size", "start_date", "end_date"],
    bodyParams: [],
    description: descriptions.searchTransactions,
    inputShape: {
      q: z.string().describe("The search query."),
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
      start_date: z.string().describe("Inclusive start date (YYYY-MM-DD).").optional(),
      end_date: z.string().describe("Inclusive end date (YYYY-MM-DD).").optional(),
    },
  },
  {
    toolName: "switch_budget_method",
    operationId: "switchBudgetMethod",
    method: "POST",
    path: "/v1/budgets/method-switch",
    isWrite: true,
    destructive: true,
    pathParams: [],
    queryParams: [],
    bodyParams: ["method", "confirm"],
    description: descriptions.switchBudgetMethod,
    inputShape: {
      method: z
        .enum([
          "fifty_thirty_twenty",
          "pay_yourself_first",
          "zero_based",
          "envelope",
          "kakeibo",
          "fire",
          "values_based",
          "custom",
        ])
        .describe("The budget method to switch to."),
      confirm: z
        .boolean()
        .describe("Must be true — the switch archives the current budget and creates a new one."),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
  {
    toolName: "update_category",
    operationId: "updateCategory",
    method: "PATCH",
    path: "/v1/categories/{id}",
    isWrite: true,
    destructive: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: ["name", "parent_id", "clear_parent", "icon", "color"],
    description: descriptions.updateCategory,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      name: z.string().optional(),
      parent_id: z.string().uuid().optional(),
      clear_parent: z.boolean().describe("Move the category to the top level.").optional(),
      icon: z.string().optional(),
      color: z.string().optional(),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
  {
    toolName: "update_goal",
    operationId: "updateGoal",
    method: "PATCH",
    path: "/v1/goals/{id}",
    isWrite: true,
    destructive: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: ["name", "description", "target_amount", "target_date"],
    description: descriptions.updateGoal,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      name: z.string().optional(),
      description: z.string().describe("Send an empty string to clear the description.").optional(),
      target_amount: z.string().describe("A decimal amount string.").optional(),
      target_date: z
        .string()
        .describe("YYYY-MM-DD, or an empty string to clear the target date.")
        .optional(),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
  {
    toolName: "update_transaction",
    operationId: "updateTransaction",
    method: "PATCH",
    path: "/v1/transactions/{id}",
    isWrite: true,
    destructive: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [
      "expected_version",
      "merchant",
      "description",
      "date",
      "amount",
      "category_id",
      "tags",
      "memo",
      "location",
      "clear_location",
      "revert_to_provider",
    ],
    description: descriptions.updateTransaction,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      expected_version: z.number().int(),
      merchant: z.string().optional(),
      description: z.string().optional(),
      date: z.string().optional(),
      amount: z
        .string()
        .describe("A decimal amount string. The row keeps the currency it settled in.")
        .optional(),
      category_id: z.string().uuid().optional(),
      tags: z
        .array(z.string())
        .describe("Replaces every tag. An empty array clears them all.")
        .optional(),
      memo: z.string().describe("An empty string clears the memo.").optional(),
      location: z
        .object({
          street: z.string().optional(),
          city: z.string().optional(),
          state: z.string().optional(),
          postal_code: z.string().optional(),
          country: z.string().optional(),
        })
        .describe(
          'A purchase location. Redacted as a single unit (transaction.location) — a city plus a postal code answers "where were you" as surely as a street line does, so the components are never hidden separately. On a write it is GROUP-REPLACE: the components sent become the whole stored location and omitted ones are cleared. Use clear_location to remove it entirely.',
        )
        .optional(),
      clear_location: z.boolean().describe("Removes the whole stored location.").optional(),
      revert_to_provider: z
        .array(z.enum(["amount", "merchant", "description", "date", "memo"]))
        .describe(
          "Restore these fields from what the bank recorded before the row's first user edit, handing ownership back to the provider so later syncs update them again. 409 when there is no captured value to revert to (an unedited row, or a manual one that never had a bank value).",
        )
        .optional(),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
];
