// AUTO-GENERATED by scripts/generate-tools.ts from openapi.yaml. DO NOT EDIT.
//
// Run `npm run generate` to regenerate. 32 tools; the write set is
// exactly the operations that declare a required Idempotency-Key header
// (update_goal, record_goal_contribution, switch_budget_method).

import { z } from "zod";
import { descriptions } from "../descriptions.js";
import type { ToolSpec } from "./types.js";

export const tools: ToolSpec[] = [
  {
    toolName: "compute_debt_payoff_plan",
    operationId: "computeDebtPayoffPlan",
    method: "POST",
    path: "/v1/debt/payoff-plan",
    isWrite: false,
    pathParams: [],
    queryParams: [],
    bodyParams: [
      "liability_ids",
      "strategy",
      "custom_order",
      "total_monthly_budget",
      "extra_monthly_payment",
    ],
    description: descriptions.computeDebtPayoffPlan,
    inputShape: {
      liability_ids: z.array(z.string().uuid()).optional(),
      strategy: z.enum(["snowball", "avalanche", "custom"]).optional(),
      custom_order: z
        .array(z.string().uuid())
        .describe("The explicit payoff order when strategy is custom.")
        .optional(),
      total_monthly_budget: z.string().describe("A decimal amount string.").optional(),
      extra_monthly_payment: z.string().describe("A decimal amount string.").optional(),
    },
  },
  {
    toolName: "get_account",
    operationId: "getAccount",
    method: "GET",
    path: "/v1/accounts/{id}",
    isWrite: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getAccount,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
    },
  },
  {
    toolName: "get_account_balances",
    operationId: "getAccountBalances",
    method: "GET",
    path: "/v1/accounts/{id}/balances",
    isWrite: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getAccountBalances,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
    },
  },
  {
    toolName: "get_budget",
    operationId: "getBudget",
    method: "GET",
    path: "/v1/budgets/{id}",
    isWrite: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getBudget,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
    },
  },
  {
    toolName: "get_budget_progress",
    operationId: "getBudgetProgress",
    method: "GET",
    path: "/v1/budgets/{id}/progress",
    isWrite: false,
    pathParams: ["id"],
    queryParams: ["month"],
    bodyParams: [],
    description: descriptions.getBudgetProgress,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      month: z
        .string()
        .describe("The month to report, as YYYY-MM. Defaults to the current month.")
        .optional(),
    },
  },
  {
    toolName: "get_cash_flow_forecast",
    operationId: "insightsCashFlowForecast",
    method: "GET",
    path: "/v1/insights/cash-flow-forecast",
    isWrite: false,
    pathParams: [],
    queryParams: ["days_ahead", "account_id"],
    bodyParams: [],
    description: descriptions.insightsCashFlowForecast,
    inputShape: {
      days_ahead: z.number().int().min(1).describe("How many days ahead to project.").optional(),
      account_id: z.string().uuid().optional(),
    },
  },
  {
    toolName: "get_debt_summary",
    operationId: "getDebtSummary",
    method: "GET",
    path: "/v1/debt/summary",
    isWrite: false,
    pathParams: [],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getDebtSummary,
    inputShape: {},
  },
  {
    toolName: "get_goal",
    operationId: "getGoal",
    method: "GET",
    path: "/v1/goals/{id}",
    isWrite: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getGoal,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
    },
  },
  {
    toolName: "get_goal_history",
    operationId: "getGoalHistory",
    method: "GET",
    path: "/v1/goals/{id}/history",
    isWrite: false,
    pathParams: ["id"],
    queryParams: ["start_date", "end_date", "resolution"],
    bodyParams: [],
    description: descriptions.getGoalHistory,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      start_date: z.string().describe("Inclusive start date (YYYY-MM-DD)."),
      end_date: z.string().describe("Inclusive end date (YYYY-MM-DD).").optional(),
      resolution: z.enum(["daily", "weekly", "monthly"]).optional(),
    },
  },
  {
    toolName: "get_goal_progress",
    operationId: "getGoalProgress",
    method: "GET",
    path: "/v1/goals/{id}/progress",
    isWrite: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getGoalProgress,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
    },
  },
  {
    toolName: "get_income_vs_expenses",
    operationId: "insightsIncomeVsExpenses",
    method: "GET",
    path: "/v1/insights/income-vs-expenses",
    isWrite: false,
    pathParams: [],
    queryParams: ["start_date", "end_date"],
    bodyParams: [],
    description: descriptions.insightsIncomeVsExpenses,
    inputShape: {
      start_date: z.string().describe("Inclusive start date (YYYY-MM-DD)."),
      end_date: z.string().describe("Inclusive end date (YYYY-MM-DD)."),
    },
  },
  {
    toolName: "get_month_summary",
    operationId: "insightsMonthSummary",
    method: "GET",
    path: "/v1/insights/month-summary",
    isWrite: false,
    pathParams: [],
    queryParams: ["month"],
    bodyParams: [],
    description: descriptions.insightsMonthSummary,
    inputShape: {
      month: z.string().describe("The month to summarize, as YYYY-MM."),
    },
  },
  {
    toolName: "get_net_worth",
    operationId: "getNetWorth",
    method: "GET",
    path: "/v1/net-worth",
    isWrite: false,
    pathParams: [],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getNetWorth,
    inputShape: {},
  },
  {
    toolName: "get_net_worth_history",
    operationId: "getNetWorthHistory",
    method: "GET",
    path: "/v1/net-worth/history",
    isWrite: false,
    pathParams: [],
    queryParams: ["period", "base_currency"],
    bodyParams: [],
    description: descriptions.getNetWorthHistory,
    inputShape: {
      period: z
        .string()
        .describe("The look-back period token (for example 30d, 6mo, 1y).")
        .optional(),
      base_currency: z
        .string()
        .describe("The ISO 4217 currency the series is converted to.")
        .optional(),
    },
  },
  {
    toolName: "get_spending_by_category",
    operationId: "insightsSpendingByCategory",
    method: "GET",
    path: "/v1/insights/spending-by-category",
    isWrite: false,
    pathParams: [],
    queryParams: ["start_date", "end_date"],
    bodyParams: [],
    description: descriptions.insightsSpendingByCategory,
    inputShape: {
      start_date: z.string().describe("Inclusive start date (YYYY-MM-DD)."),
      end_date: z.string().describe("Inclusive end date (YYYY-MM-DD)."),
    },
  },
  {
    toolName: "get_sync_status",
    operationId: "getSyncStatus",
    method: "GET",
    path: "/v1/sync-status",
    isWrite: false,
    pathParams: [],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getSyncStatus,
    inputShape: {},
  },
  {
    toolName: "get_transaction",
    operationId: "getTransaction",
    method: "GET",
    path: "/v1/transactions/{id}",
    isWrite: false,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: [],
    description: descriptions.getTransaction,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
    },
  },
  {
    toolName: "list_accounts",
    operationId: "listAccounts",
    method: "GET",
    path: "/v1/accounts",
    isWrite: false,
    pathParams: [],
    queryParams: ["cursor", "page_size", "connection_id"],
    bodyParams: [],
    description: descriptions.listAccounts,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
      connection_id: z
        .string()
        .uuid()
        .describe("Filter to accounts under a single bank connection.")
        .optional(),
    },
  },
  {
    toolName: "list_budgets",
    operationId: "listBudgets",
    method: "GET",
    path: "/v1/budgets",
    isWrite: false,
    pathParams: [],
    queryParams: ["cursor", "page_size", "active"],
    bodyParams: [],
    description: descriptions.listBudgets,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
      active: z.boolean().describe("When true, return only active budgets.").optional(),
    },
  },
  {
    toolName: "list_categories",
    operationId: "listCategories",
    method: "GET",
    path: "/v1/categories",
    isWrite: false,
    pathParams: [],
    queryParams: [],
    bodyParams: [],
    description: descriptions.listCategories,
    inputShape: {},
  },
  {
    toolName: "list_connections",
    operationId: "listConnections",
    method: "GET",
    path: "/v1/connections",
    isWrite: false,
    pathParams: [],
    queryParams: ["cursor", "page_size"],
    bodyParams: [],
    description: descriptions.listConnections,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
    },
  },
  {
    toolName: "list_goal_contributions",
    operationId: "getGoalContributions",
    method: "GET",
    path: "/v1/goals/{id}/contributions",
    isWrite: false,
    pathParams: ["id"],
    queryParams: ["cursor", "page_size"],
    bodyParams: [],
    description: descriptions.getGoalContributions,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
    },
  },
  {
    toolName: "list_goals",
    operationId: "listGoals",
    method: "GET",
    path: "/v1/goals",
    isWrite: false,
    pathParams: [],
    queryParams: ["cursor", "page_size"],
    bodyParams: [],
    description: descriptions.listGoals,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
    },
  },
  {
    toolName: "list_holdings",
    operationId: "listHoldings",
    method: "GET",
    path: "/v1/holdings",
    isWrite: false,
    pathParams: [],
    queryParams: ["cursor", "page_size", "account_id"],
    bodyParams: [],
    description: descriptions.listHoldings,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
      account_id: z.string().uuid().optional(),
    },
  },
  {
    toolName: "list_liabilities",
    operationId: "listLiabilities",
    method: "GET",
    path: "/v1/liabilities",
    isWrite: false,
    pathParams: [],
    queryParams: ["cursor", "page_size", "account_id"],
    bodyParams: [],
    description: descriptions.listLiabilities,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
      account_id: z.string().uuid().optional(),
    },
  },
  {
    toolName: "list_recurring",
    operationId: "listRecurring",
    method: "GET",
    path: "/v1/recurring",
    isWrite: false,
    pathParams: [],
    queryParams: ["cursor", "page_size"],
    bodyParams: [],
    description: descriptions.listRecurring,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
    },
  },
  {
    toolName: "list_transactions",
    operationId: "listTransactions",
    method: "GET",
    path: "/v1/transactions",
    isWrite: false,
    pathParams: [],
    queryParams: [
      "cursor",
      "page_size",
      "account_id",
      "category_id",
      "start_date",
      "end_date",
      "pending",
      "source",
      "uncategorized",
    ],
    bodyParams: [],
    description: descriptions.listTransactions,
    inputShape: {
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
      account_id: z.string().uuid().optional(),
      category_id: z.string().uuid().optional(),
      start_date: z.string().describe("Inclusive start date (YYYY-MM-DD).").optional(),
      end_date: z.string().describe("Inclusive end date (YYYY-MM-DD).").optional(),
      pending: z
        .boolean()
        .describe("When set, filter to pending (true) or posted (false) transactions.")
        .optional(),
      source: z.enum(["bank_sync", "manual", "import"]).optional(),
      uncategorized: z
        .boolean()
        .describe("When true, return only transactions with no category.")
        .optional(),
    },
  },
  {
    toolName: "list_upcoming_bills",
    operationId: "listUpcomingBills",
    method: "GET",
    path: "/v1/bills/upcoming",
    isWrite: false,
    pathParams: [],
    queryParams: ["days_ahead"],
    bodyParams: [],
    description: descriptions.listUpcomingBills,
    inputShape: {
      days_ahead: z.number().int().min(1).describe("How many days ahead to project.").optional(),
    },
  },
  {
    toolName: "record_goal_contribution",
    operationId: "recordGoalContribution",
    method: "POST",
    path: "/v1/goals/{id}/contributions",
    isWrite: true,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: ["amount", "currency_code", "note", "period_start"],
    description: descriptions.recordGoalContribution,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      amount: z.string().describe("A positive decimal amount string."),
      currency_code: z
        .string()
        .describe("ISO 4217 code. Defaults to the goal's currency when omitted.")
        .optional(),
      note: z.string().optional(),
      period_start: z
        .string()
        .describe("The budget period (YYYY-MM-DD, first of month). Defaults to the current month.")
        .optional(),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
  {
    toolName: "search_transactions",
    operationId: "searchTransactions",
    method: "GET",
    path: "/v1/transactions/search",
    isWrite: false,
    pathParams: [],
    queryParams: ["q", "cursor", "page_size", "start_date", "end_date"],
    bodyParams: [],
    description: descriptions.searchTransactions,
    inputShape: {
      q: z.string().describe("The search query."),
      cursor: z
        .string()
        .describe("Opaque cursor from a previous response's pagination.next_cursor.")
        .optional(),
      page_size: z.number().int().min(1).describe("Maximum number of items to return.").optional(),
      start_date: z.string().describe("Inclusive start date (YYYY-MM-DD).").optional(),
      end_date: z.string().describe("Inclusive end date (YYYY-MM-DD).").optional(),
    },
  },
  {
    toolName: "switch_budget_method",
    operationId: "switchBudgetMethod",
    method: "POST",
    path: "/v1/budgets/method-switch",
    isWrite: true,
    pathParams: [],
    queryParams: [],
    bodyParams: ["method", "confirm"],
    description: descriptions.switchBudgetMethod,
    inputShape: {
      method: z
        .enum([
          "fifty_thirty_twenty",
          "pay_yourself_first",
          "zero_based",
          "envelope",
          "kakeibo",
          "fire",
          "values_based",
          "custom",
        ])
        .describe("The budget method to switch to."),
      confirm: z
        .boolean()
        .describe("Must be true — the switch archives the current budget and creates a new one."),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
  {
    toolName: "update_goal",
    operationId: "updateGoal",
    method: "PATCH",
    path: "/v1/goals/{id}",
    isWrite: true,
    pathParams: ["id"],
    queryParams: [],
    bodyParams: ["name", "description", "target_amount", "target_date"],
    description: descriptions.updateGoal,
    inputShape: {
      id: z.string().uuid().describe("The resource UUID."),
      name: z.string().optional(),
      description: z.string().describe("Send an empty string to clear the description.").optional(),
      target_amount: z.string().describe("A decimal amount string.").optional(),
      target_date: z
        .string()
        .describe("YYYY-MM-DD, or an empty string to clear the target date.")
        .optional(),
      idempotency_key: z
        .string()
        .min(1)
        .max(128)
        .optional()
        .describe(
          "Optional idempotency key (1-128 chars) that makes this write safe to retry: a repeated call with the same key replays the original result. If omitted, a random one is generated for this call.",
        ),
    },
  },
];
